vgks_sigtran_homepage:
    path:     /
    defaults: { _controller: VgksSigtranBundle:Default:index }

vgks_sigtran_material_show:
    path:     /material/{id}
    defaults: { _controller: VgksSigtranBundle:Material:show }

vgks_sigtran_material_add:
    path:     /material/add
    defaults: { _controller: VgksSigtranBundle:Material:add }

vgks_sigtran_material_edit:
    path:     /material/edit/{id}
    defaults: { _controller: VgksSigtranBundle:Material:edit }