vgks_sigtran_homepage:
    path:     /
    defaults: { _controller: VgksSigtranBundle:Default:index }

vgks_sigtran_success:
    path:     /success
    defaults: { _controller: VgksSigtranBundle:Default:success }

vgks_sigtran_material_all:
    path:     /material
    defaults: { _controller: VgksSigtranBundle:Material:all }

vgks_sigtran_material_show:
    path:     /material/{id}
    defaults: { _controller: VgksSigtranBundle:Material:show }
    requirements:
        id: \d+

vgks_sigtran_material_add:
    path:     /admin/material/add
    defaults: { _controller: VgksSigtranBundle:Material:add }

vgks_sigtran_material_edit:
    path:     /admin/material/edit/{id}
    defaults: { _controller: VgksSigtranBundle:Material:edit }
    requirements:
        id: \d+

vgks_sigtran_material_delete:
    path:     /admin/material/delete/{id}
    defaults: { _controller: VgksSigtranBundle:Material:delete }
    requirements:
        id: \d+

vgks_sigtran_question_all:
    path:     /question
    defaults: { _controller: VgksSigtranBundle:Question:all }

vgks_sigtran_question_show:
    path:     /question/{id}
    defaults: { _controller: VgksSigtranBundle:Question:show }
    requirements:
        id: \d+

vgks_sigtran_question_add:
    path:     /admin/question/add
    defaults: { _controller: VgksSigtranBundle:Question:add }

vgks_sigtran_question_edit:
    path:     /admin/question/edit/{id}
    defaults: { _controller: VgksSigtranBundle:Question:edit }
    requirements:
        id: \d+

vgks_sigtran_question_delete:
    path:     /admin/question/delete/{id}
    defaults: { _controller: VgksSigtranBundle:Question:delete }
    requirements:
        id: \d+

vgks_sigtran_test_show:
    path:     /test/show
    defaults: { _controller: VgksSigtranBundle:Test:show }

vgks_sigtran_test_check:
    path:     /test/check
    defaults: { _controller: VgksSigtranBundle:Test:check }

vgks_sigtran_admin:
    path:     /admin
    defaults: { _controller: VgksSigtranBundle:Admin:index }
