vgks_sigtran_homepage:
    path:     /
    defaults: { _controller: VgksSigtranBundle:Default:index }

vgks_sigtran_success:
    path:     /success
    defaults: { _controller: VgksSigtranBundle:Default:success }

vgks_sigtran_material_show:
    path:     /material/{id}
    defaults: { _controller: VgksSigtranBundle:Material:show }
    requirements:
        id: \d+

vgks_sigtran_material_add:
    path:     /material/add
    defaults: { _controller: VgksSigtranBundle:Material:add }

vgks_sigtran_material_edit:
    path:     /material/edit/{id}
    defaults: { _controller: VgksSigtranBundle:Material:edit }
    requirements:
        id: \d+

vgks_sigtran_material_delete:
    path:     /material/delete/{id}
    defaults: { _controller: VgksSigtranBundle:Material:delete }
    requirements:
        id: \d+

vgks_sigtran_question_show:
    path:     /question/{id}
    defaults: { _controller: VgksSigtranBundle:Question:show }
    requirements:
        id: \d+

vgks_sigtran_question_add:
    path:     /question/add
    defaults: { _controller: VgksSigtranBundle:Question:add }

vgks_sigtran_question_edit:
    path:     /question/edit/{id}
    defaults: { _controller: VgksSigtranBundle:Question:edit }
    requirements:
        id: \d+

vgks_sigtran_question_delete:
    path:     /question/delete/{id}
    defaults: { _controller: VgksSigtranBundle:Question:delete }
    requirements:
        id: \d+
