vgks_sigtran_homepage:
    path:     /
    defaults: { _controller: VgksSigtranBundle:Default:index }

vgks_sigtran_material_show:
    path:     /material/{id}
    defaults: { _controller: VgksSigtranBundle:Material:show }
    requirements:
        id: \d+

vgks_sigtran_material_add:
    path:     /material/add
    defaults: { _controller: VgksSigtranBundle:Material:add }

vgks_sigtran_material_edit:
    path:     /material/edit/{id}
    defaults: { _controller: VgksSigtranBundle:Material:edit }

vgks_sigtran_material_success:
    path:     /material/success
    defaults: { _controller: VgksSigtranBundle:Material:success }

vgks_sigtran_question_add:
    path:     /question/add
    defaults: { _controller: VgksSigtranBundle:Question:add }

vgks_sigtran_question_success:
    path:     /question/success
    defaults: { _controller: VgksSigtranBundle:Question:success }

