services:
#    vgks_sigtran.example:
#        class: Vgks\SigtranBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    vgks_sigtran.form.type.material:
            class: Vgks\SigtranBundle\Form\Type\MaterialType
            tags:
                - { name: form.type, alias: material }

    vgks_sigtran.form.type.question:
                class: Vgks\SigtranBundle\Form\Type\QuestionType
                tags:
                    - { name: form.type, alias: question }
